"""Add supplier and GST fields

Revision ID: 52fb8834cd58
Revises: 
Create Date: 2026-02-18 21:50:01.365411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52fb8834cd58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_items')
    op.drop_table('prescriptions')
    op.drop_table('deliveries')
    op.drop_index(op.f('idx_stock_item'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('purchases')
    op.drop_index(op.f('idx_items_barcode'), table_name='items')
    op.drop_table('items')
    op.drop_table('lens_order_status_log')
    op.drop_table('roles')
    op.drop_table('suppliers')
    op.drop_table('users')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('purchase_items')
    op.drop_index(op.f('idx_sales_date'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('payments')
    op.drop_index(op.f('idx_lens_status'), table_name='lens_orders')
    op.drop_table('lens_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lens_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prescription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lens_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('index_value', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('coating', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tint', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expected_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('lens_orders_prescription_id_fkey')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('lens_orders_sale_id_fkey')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('lens_orders_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lens_orders_pkey'))
    )
    op.create_index(op.f('idx_lens_status'), 'lens_orders', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('payments_sale_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('paid', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('sales_created_by_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('sales_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_pkey'))
    )
    op.create_index(op.f('idx_sales_date'), 'sales', ['date'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('purchase_items_item_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('purchase_items_purchase_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_items_pkey'))
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('uhid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customers_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('users_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gstin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('suppliers_pkey'))
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
    sa.UniqueConstraint('name', name=op.f('roles_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('lens_order_status_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lens_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('lens_order_status_log_changed_by_fkey')),
    sa.ForeignKeyConstraint(['lens_order_id'], ['lens_orders.id'], name=op.f('lens_order_status_log_lens_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lens_order_status_log_pkey'))
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('selling_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('stock_qty', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('reorder_level', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('items_category_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey')),
    sa.UniqueConstraint('barcode', name=op.f('items_barcode_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_items_barcode'), 'items', ['barcode'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('purchases_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchases_pkey'))
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('change_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('stock_movements_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_movements_pkey'))
    )
    op.create_index(op.f('idx_stock_item'), 'stock_movements', ['item_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expected_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('deliveries_sale_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deliveries_pkey'))
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sphere_r', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cyl_r', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('axis_r', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('add_r', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('sphere_l', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cyl_l', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('axis_l', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('add_l', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('pd', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('prescriptions_sale_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('prescriptions_pkey'))
    )
    op.create_table('sale_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('taxable_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('cgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('sgst', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('sale_items_item_id_fkey')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('sale_items_sale_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_items_pkey'))
    )
    # ### end Alembic commands ###
